### ISSUE TITLE
Benchmarks don't work

### ISSUE THREAD

**Issue by farwayer** [selfrefactor/rambda#463]
Error if uncomment `runSingleBenchmark()` or `runAllBenchmarks()` in `scripts/all-scripts/all-scripts.spec.js`:
```js
TypeError: Cannot read property 'parentNode' of undefined

      at runScript (node_modules/benchmark/benchmark.js:664:28)
      at createFunction (node_modules/benchmark/benchmark.js:517:9)
      at createFunction (node_modules/benchmark/benchmark.js:524:44)
      at createCompiled (node_modules/benchmark/benchmark.js:1714:23)
      at clock (node_modules/benchmark/benchmark.js:1608:58)
      at clock (node_modules/benchmark/benchmark.js:1818:20)
      at cycle (node_modules/benchmark/benchmark.js:2007:49)
      at Benchmark.run (node_modules/benchmark/benchmark.js:2114:13)
      at execute (node_modules/benchmark/benchmark.js:860:74)
      at invoke (node_modules/benchmark/benchmark.js:970:20)
      at compute (node_modules/benchmark/benchmark.js:1966:7)
      at Benchmark.run (node_modules/benchmark/benchmark.js:2119:11)
      at execute (node_modules/benchmark/benchmark.js:860:74)
      at invoke (node_modules/benchmark/benchmark.js:970:20)
      at Suite.runSuite [as run] (node_modules/benchmark/benchmark.js:1169:7)
      at node_modules/benny/lib/suite.js:29:14
      at node_modules/benny/lib/suite.js:25:12
      at fulfilled (node_modules/benny/lib/suite.js:5:58)
```

**Comment by selfrefactor** [comment]
It is a valid bug. I will look into it.

**Comment by selfrefactor** [comment]
Up until now, I didn't now that Jest's default test environment is `jsdom`. Thank you. Please try now, it should work.

**Comment by farwayer** [comment]
It works now! Thanks.
