### ISSUE TITLE
equals crashing on parseError

### ISSUE THREAD

**Issue by eikooc** [selfrefactor/rambda#704]
### Issue
When I try to use the `equals` operator on two objects, I get a _parseError_.

```js
import * as R from "https://x.nest.land/rambda@7.5.0/mod.ts";

const rEquals = R.equals(
  {
    a: { b: 1 },
  },
  {
    a: { b: 1 },
  },
);
console.log(rEquals);
```

Error:
```js
error: Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
  const typeofError = maybeError.__proto__.toString()
                                           ^
    at parseError (https://mckgnjtrq3abdh6fhic5ddwopjdoxtpu2vvkyphhzwui4egizoma.arweave.net/YJRmpnGGwBGfxToF0Y7OekbrzfTVaqw8582ojhDIy5g/src/equals.js:69:44)
    at Module.equals (https://mckgnjtrq3abdh6fhic5ddwopjdoxtpu2vvkyphhzwui4egizoma.arweave.net/YJRmpnGGwBGfxToF0Y7OekbrzfTVaqw8582ojhDIy5g/src/equals.js:146:18)
    at file:///home/user/Code/Code%20Experiments/deno/rambda/main.ts:3:19
```

### Rambda version
7.5.0

### Node.js version
Using Deno

**Comment by selfrefactor** [comment]
interesting; I will check
txs

**Comment by selfrefactor** [comment]
I found a fix, but we'll have to wait to test it on released version, so I will keep it open till then,

**Comment by selfrefactor** [comment]
Closing this as new version 8.5.0 is fixing this. Let me know if that is not the case.
